title = "Roact-Hooks Bag"
gitRepoUrl = "https://github.com/Rimuy/hook-bag"
gitSourceBranch = "master"

classOrder = ["Hooks"]

# [[classOrder]]
# section = "A"
# classes = ["Hooks"]

[docusaurus]
url = "https://rimuy.github.io"
baseUrl = "/hook-bag/"
tagline = "Collection of custom roact hooks"

[home]
enabled = true
includeReadme = true